# Generated by Django 6.0.2 on 2026-04-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('medidas', models.CharField(max_length=255)),
                ('orientacion', models.IntegerField(choices=[(1, 'Corto'), (2, 'Largo')], default=2)),
                ('color', models.BooleanField(default=False)),
                ('aislacion', models.BooleanField(default=False)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('resultado', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
